name = "remix-cloudflare-db"
compatibility_date = "2024-09-25"
pages_build_output_dir = "./build/client"

[[d1_databases]]
binding = "DB"
database_name = "budget-app"
database_id = "27bced39-2238-43f1-8da5-62725235c19b"

